[env:wt32-sc01]
platform = espressif32@6.11.0
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200

board_build.partitions = huge_app.csv
board_build.psram = enabled

build_flags = 
	-DUSE_ST7735
	-DBOARD_HAS_PSRAM
    -DCONFIG_SPIRAM_ALLOW_STACK_EXTERNAL_MEMORY=1
	-mfix-esp32-psram-cache-issue
	-DLV_CONF_INCLUDE_SIMPLE
	-DCONFIG_SPIRAM_SUPPORT
    -DCONFIG_SPIRAM_USE_CAPS_ALLOC
	-I src/
	
build_src_filter =
	+<*>
	-<main_research.cpp>
	-<main.cpp>
	-<main3RAM.cpp>

lib_deps = 
	lovyan03/LovyanGFX@^1.2.0
	lvgl/lvgl@^8.1.0
	https://github.com/pschatzmann/ESP32-A2DP
	https://github.com/pschatzmann/arduino-audio-tools.git
	https://github.com/pschatzmann/arduino-libhelix.git
	thomasfredericks/Bounce2@^2.72
	https://github.com/madhephaestus/ESP32Encoder.git

[env:wt32-sc01_debugger]
platform = https://github.com/platformio/platform-espressif32.git#feature/arduino-upstream
board = esp-wrover-kit
framework = arduino
upload_speed = 921600
monitor_speed = 115200
debug_tool = esp-prog
upload_protocol = esp-prog
debug_init_break = tbreak setup
debug_speed = 1000
build_type = debug
debug_build_flags = -O0 -g -ggdb

board_build.partitions = huge_app.csv


build_flags = 
	-DUSE_ST7735
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-DLV_CONF_INCLUDE_SIMPLE
	-DCONFIG_SPIRAM_SUPPORT
    -DCONFIG_SPIRAM_USE_CAPS_ALLOC
	-I src/
	
build_src_filter =
	+<*>

lib_deps = 
	lovyan03/LovyanGFX@^1.2.0
	lvgl/lvgl@^8.1.0
	https://github.com/pschatzmann/ESP32-A2DP
	https://github.com/pschatzmann/arduino-audio-tools.git
	https://github.com/pschatzmann/arduino-libhelix.git
	thomasfredericks/Bounce2@^2.72
	https://github.com/madhephaestus/ESP32Encoder.git


[env:wroom]
platform = espressif32@6.11.0
board = esp32dev
framework = arduino
upload_speed = 921600
monitor_speed = 115200

board_build.partitions = huge_app.csv

build_flags = 
	-DUSE_ST7735
	-DNO_PSRAM
	-DLV_CONF_INCLUDE_SIMPLE
	-I src/
	
build_src_filter =
	+<*>

lib_deps = 
	lovyan03/LovyanGFX@^1.2.0
	lvgl/lvgl@^8.1.0
	https://github.com/pschatzmann/ESP32-A2DP
	https://github.com/pschatzmann/arduino-audio-tools.git
	https://github.com/pschatzmann/arduino-libhelix.git
	thomasfredericks/Bounce2@^2.72
	https://github.com/madhephaestus/ESP32Encoder.git
